use springweb2;
SET SQL_SAFE_UPDATES = 0; -- UPDATE 사용 설정

# 트랜잭션
# 자동 commit 비활성화 설정
SET AUTOCOMMIT = 0;

# 트랜잭션 시작
START TRANSACTION;
# 작업 (DML)
UPDATE TRANS SET MONEY = MONEY - 30000 WHERE NAME = '신동엽';
UPDATE TRANS SET MONEY = MONEY + 30000 WHERE NAME = '서장훈';
# 되돌리기
ROLLBACK;
# 완료
COMMIT;
SELECT * FROM TRANS;

START TRANSACTION;
# 작업
UPDATE TRANS SET MONEY = MONEY - 30000 WHERE NAME = '신동엽';
# 저장 지점 만들기
SAVEPOINT P1;
# 작업 2
UPDATE TRANS SET MONEY = MONEY + 30000 WHERE NAME = '서장훈';
COMMIT;
# 특정 지점으로 롤백
ROLLBACK TO P1;
SELECT * FROM TRANS;

# JAVA SPRING : @TRANSACTIONAL 사용하여 RuntimeException 으로 롤백. SAVEPOINT 지원하지 않음)
# JAVA JDBC(DAO) : 모두 지원

START TRANSACTION;
# 1
UPDATE TRANS SET MONEY = MONEY + 30000 WHERE NAME = '신동엽';
SAVEPOINT S1;
# 2
UPDATE TRANS SET MONEY = MONEY - 30000 WHERE NAME = '서장훈';
SAVEPOINT S2;
# 3
UPDATE TRANS SET MONEY = MONEY - 10000 WHERE NAME = '서장훈';
SAVEPOINT S3;
ROLLBACK TO S1; -- 1까지 반영
ROLLBACK TO S2; -- 1, 2까지 반영
ROLLBACK TO S3; -- 1, 2, 3까지 반영
COMMIT;
SELECT * FROM TRANS;